### ISSUE TITLE
Crate does no longer work with no-std on 0.7

### ISSUE THREAD

**Issue by Luro02** [colin-kiegel/rust-pretty-assertions#82]
It fails with:
```
error[E0433]: failed to resolve: could not find `std` in the list of imported crates
  --> src\sanitizers\deduplicator.rs:74:9
   |
74 |         assert_eq!(iter.next(), Some('1'));
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `std` in the list of imported crates
   |
   = note: this error originates in the macro `assert_eq` (in Nightly builds, run with -Z macro-backtrace for more info)
```
(feature gating every single test with the std feature would be really annoying, especially when the std feature is disabled by default)

The macro expands in `0.7` to something like this:
```rust
{
    match (&(sanitizer.next()), &(None)) {
        (left_val, right_val) => {
            if !(*left_val == *right_val) {
                {
                    ::std::rt::begin_panic_fmt(&match match (
                        &::pretty_assertions::Comparison::new(left_val, right_val),
                    ) {
                        (arg0,) => [::core::fmt::ArgumentV1::new(
                            arg0,
                            ::core::fmt::Display::fmt,
                        )],
                    } {
                        ref args => unsafe {
                            ::core::fmt::Arguments::new_v1(
                                &["assertion failed: `(left == right)`\n\n", "\n"],
                                args,
                            )
                        },
                    })
                }
            }
        }
    }
};
```

Previously (`0.6`), it expanded to
```rust
{
    match (&(sanitizer.next()), &(None)) {
        (left_val, right_val) => {
            if !(*left_val == *right_val) {
                ::core::panicking::panic_fmt(
                    match match (&::pretty_assertions::Comparison::new(
                        left_val, right_val,
                    ),)
                    {
                        (arg0,) => [::core::fmt::ArgumentV1::new(
                            arg0,
                            ::core::fmt::Display::fmt,
                        )],
                    } {
                        ref args => unsafe {
                            ::core::fmt::Arguments::new_v1(
                                &["assertion failed: `(left == right)`\n\n", "\n"],
                                args,
                            )
                        },
                    },
                )
            }
        }
    }
};
```

Related issue: KokaKiwi/rust-hex#63

**Comment by tommilligan** [comment]
Hey, thanks for the report. I've put together a PR which I think should provide no_std support, as long as you still have an allocator: https://github.com/colin-kiegel/rust-pretty-assertions/pull/83

I don't have masses of experience with `no_std` support - if you could verify this fix works for your use case, I'll be able to merge and release it faster. You can try out the patch with something like:

```toml
pretty_assertions = { git="https://github.com/tommilligan/rust-pretty-assertions", rev="9ba9e84d930493f0218615919ec3868c6d36f47b" }

**Comment by Luro02** [comment]
Thank you, this does work as expected

**Comment by tommilligan** [comment]
Closed as released in v1.0.0
